# Generated by Django 4.1 on 2022-08-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0020_person_about_me_person_life_credo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAdministrativePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_position', models.CharField(help_text='приклад: Директор гімназії | Заступник директора з навчально-виховної роботи...', max_length=64, unique=True, verbose_name='посада')),
            ],
            options={
                'verbose_name_plural': 'Види адміністративної посади',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='працівник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.typeofadministrativeposition', verbose_name='посада')),
            ],
            options={
                'verbose_name_plural': 'Адміністрація',
            },
        ),
    ]
