# Generated by Django 4.1 on 2022-08-22 11:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0020_person_about_me_person_life_credo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='перше слово має бути з великої літери', max_length=64, unique=True, verbose_name='назва')),
                ('image', models.ImageField(help_text='фото має бути розміром 600x400 px', upload_to='categories', verbose_name='зображення')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField()),
                ('date_created', models.DateField(verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публікувати')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.person', verbose_name='автор')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.categories', verbose_name='категорія')),
            ],
            options={
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='ImageOfPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_of_post/%Y/%m', verbose_name='зображення')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='новина')),
            ],
            options={
                'verbose_name_plural': 'Зображення для новин',
            },
        ),
    ]
