# Generated by Django 4.1 on 2022-08-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
