# Generated by Django 4.1 on 2022-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberated', models.BooleanField(default=False, verbose_name='звільнений?')),
                ('lastname', models.CharField(max_length=32, verbose_name='прізвище')),
                ('firstname', models.CharField(max_length=32, verbose_name="ім'я")),
                ('patronymic', models.CharField(max_length=32, verbose_name='по батькові')),
                ('photo', models.ImageField(blank=True, help_text='фото має бути розміром 300x300 px', null=True, upload_to='staff', verbose_name='фото')),
                ('birthday', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='телефон')),
                ('other_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='додатковий телефон')),
            ],
            options={
                'verbose_name_plural': 'Персона',
            },
        ),
    ]
