# Generated by Django 4.1 on 2022-08-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_socialnetworkofuser_typeofsocialnetwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAdministrativePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_position', models.CharField(help_text='приклад: Директор гімназії | Заступник директора з навчально-виховної роботи...', max_length=64, verbose_name='посада')),
            ],
            options={
                'verbose_name_plural': 'Види адміністративної посади',
            },
        ),
        migrations.AlterModelOptions(
            name='socialnetworkofuser',
            options={'verbose_name_plural': 'Соціальні мережі користувачів'},
        ),
        migrations.AlterModelOptions(
            name='typeofsocialnetwork',
            options={'verbose_name_plural': 'Види соціальних мереж'},
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(0, 'жіноча'), (1, 'чоловіча')], default=0, max_length=36, verbose_name='стать'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialnetworkofuser',
            name='type_of_social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typeofsocialnetwork', verbose_name='Вид соціальної мережі'),
        ),
        migrations.AlterField(
            model_name='typeofsocialnetwork',
            name='class_name',
            field=models.CharField(help_text='назви класів шукайте за посиланням https://fortawesome.com/sets/font-awesome-5-brands', max_length=32, verbose_name="ім'я класу"),
        ),
        migrations.AlterField(
            model_name='typeofsocialnetwork',
            name='name',
            field=models.CharField(max_length=32, verbose_name='назва'),
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typeofadministrativeposition')),
            ],
            options={
                'verbose_name_plural': 'Адміністрація',
            },
        ),
    ]
