# Generated by Django 4.1 on 2022-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_rename_person_administration_person_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetworkofuser',
            old_name='social_network',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='liberated',
            field=models.BooleanField(default=True, verbose_name='працює'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('woman', 'жіноча'), ('man', 'чоловіча')], max_length=36, verbose_name='стать'),
        ),
    ]
