# Generated by Django 4.1 on 2022-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_delete_administration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsocialnetwork',
            name='class_name',
            field=models.CharField(help_text='назви класів шукайте за посиланням https://fortawesome.com/sets/font-awesome-5-brands or https://fontawesome.com/', max_length=32, verbose_name="ім'я класу"),
        ),
    ]
