# Generated by Django 4.1 on 2022-08-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_socialnetwork_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.socialnetwork'),
        ),
    ]
