# Generated by Django 4.1 on 2022-08-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_person_social_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='social_network',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='social_network',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='staff.person'),
            preserve_default=False,
        ),
    ]
