# Generated by Django 4.1 on 2022-08-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_person_social_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person')),
            ],
            options={
                'verbose_name_plural': 'Соціальна мережа користувача',
            },
        ),
        migrations.CreateModel(
            name='TypeOfSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('class_name', models.CharField(help_text='назви класів шукайте за посиланням https://fortawesome.com/sets/font-awesome-5-brands', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
        migrations.AddField(
            model_name='socialnetworkofuser',
            name='type_of_social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typeofsocialnetwork'),
        ),
    ]
