# Generated by Django 4.1 on 2022-08-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_typeofadministrativeposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='person_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person', unique=True, verbose_name='працівник'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typeofadministrativeposition', verbose_name='посада'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('man', 'жіноча'), ('woman', 'чоловіча')], max_length=36, verbose_name='стать'),
        ),
    ]
