# Generated by Django 4.1 on 2022-08-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_administration_person_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='person_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='працівник'),
        ),
    ]
