# Generated by Django 4.1 on 2022-08-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_administration_person_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='person_admin',
            new_name='person',
        ),
    ]
