# Generated by Django 4.1 on 2022-08-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_rename_person_admin_administration_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='person',
            new_name='person_admin',
        ),
    ]
