# Generated by Django 4.1 on 2022-08-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_social_network_socialnetworkofuser_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='TypeOfAdministrativePosition',
        ),
    ]
