# Generated by Django 4.1 on 2022-08-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_typeofsocialnetwork_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='фото має бути розміром 300x300 px', upload_to='staff', verbose_name='фото'),
        ),
    ]
