# Generated by Django 4.1 on 2022-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='', help_text='фото має бути розміром 300x300 px', null=True, upload_to='staff', verbose_name='фото'),
        ),
    ]
