# Generated by Django 4.1 on 2022-08-20 16:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_alter_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Про себе'),
        ),
        migrations.AddField(
            model_name='person',
            name='life_credo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Життєве кредо'),
        ),
    ]
