# Generated by Django 4.1 on 2022-08-22 11:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='назава')),
                ('image', models.ImageField(upload_to='image_of_page', verbose_name='зображення')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата завантаження')),
            ],
            options={
                'verbose_name_plural': 'Зображення для сторінок',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='назава')),
                ('relative_link', models.SlugField(help_text='посилання не має містити лише латинські літери, цифри та символ ніжнього підкреслення, приклад: video_gallery', max_length=64, unique=True, verbose_name='відносне посилання')),
                ('body', tinymce.models.HTMLField(help_text='після створення сторінки не забудьте додати її в меню')),
            ],
            options={
                'verbose_name_plural': 'Сторінки',
            },
        ),
    ]
