# Generated by Django 4.1 on 2022-08-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0020_person_about_me_person_life_credo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='назва')),
                ('mass', models.SmallIntegerField(default=0, help_text='ранг має бути унікальним для кожногї категорії', unique=True, verbose_name='ранг')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='приклад: математика', max_length=64, unique=True, verbose_name='назва')),
                ('genitive_case_of_name', models.CharField(help_text='приклад: математики', max_length=64, unique=True, verbose_name='родовий відмінок')),
            ],
            options={
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='назва')),
            ],
            options={
                'verbose_name_plural': 'Звання',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.category', verbose_name='категорія')),
                ('lessons', models.ManyToManyField(blank=True, to='teachers.lesson', verbose_name='уроки')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='Працівник')),
                ('ranks', models.ManyToManyField(blank=True, to='teachers.rank', verbose_name='звання')),
            ],
            options={
                'verbose_name_plural': 'Вчителі',
            },
        ),
    ]
