# Generated by Django 4.1 on 2022-08-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0020_person_about_me_person_life_credo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Назва')),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Платформа',
            },
        ),
        migrations.CreateModel(
            name='TypeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': 'Тип документу',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Назва')),
                ('link', models.CharField(max_length=256)),
                ('number_of_hours', models.FloatField(blank=True, null=True, verbose_name='Кількість годин')),
                ('date', models.DateField(verbose_name='Дата видачі')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='Працівник')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.platform', verbose_name='Платформа')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.typedoc', verbose_name='Тип документу')),
            ],
            options={
                'verbose_name_plural': 'Сертифікати',
            },
        ),
    ]
